// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BugsManager.Models.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace BugsManager.Models
{
    public partial class BugsManagerContext : DbContext
    {
        public BugsManagerContext()
        {
        }

        public BugsManagerContext(DbContextOptions<BugsManagerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Bug> Bug { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.BugConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
