// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace BugsManager.Models
{
    public partial class Project
    {
        public Project()
        {
            Bug = new HashSet<Bug>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; } = default!;
        [StringLength(100)]
        public string? Description { get; set; }

        [InverseProperty("Project")]
        public virtual ICollection<Bug> Bug { get; set; }
    }
}