// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace BugsManager.Models
{
    public partial class User
    {
        public User()
        {
            Bug = new HashSet<Bug>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; } = default!;
        [Required]
        [StringLength(100)]
        public string Surname { get; set; } = default!;

        [InverseProperty("User")]
        public virtual ICollection<Bug> Bug { get; set; }
    }
}